import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "~/components/personals/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ascendix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#050814] dark`}>
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
